### ISSUE TITLE
关于分块上传

### ISSUE THREAD

**Issue by Xiazhm** [shady-xia/vue-uploader-solutions#1]
你的代码中没有写到什么获取文件md5字符串，什么时候通知后台合并文件，是怎么做到分块上传的。在后台接口做的处理么

**Comment by shady-xia** [comment]
在uploadStart事件中可以用h5的FileReader来读取文件来生成MD5，发给后台判断可否秒传或断点续传；
后台在每个分片上传完时，会给前台发一个字段，比如叫needMerge，所有分片上传完时，后台返回的needMerge为true，这个时候你可以发个请求通知后台合并文件
