### ISSUE TITLE
Property or method "attrs" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by wangpai1998** [shady-xia/vue-uploader-solutions#10]
这个怎么解决？  那些值都提示出来了
Property or method "attrs" is not defined on the instance but referenced during render

Property or method "panelShow" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by shady-xia** [comment]
你忘了在data中声明attrs和panelShow了吧
