### ISSUE TITLE
autoStart设为false以后要在点击上传时上传应该调哪个方法？

### ISSUE THREAD

**Issue by FuhuaChen** [shady-xia/vue-uploader-solutions#11]

**Comment by FuhuaChen** [comment]
设置不自动上传以后，没有办法主动触发上传吗？

**Comment by shady-xia** [comment]
file.resume()

**Comment by FuhuaChen** [comment]
但是，当我设置自动上传的时候是可以正常上传的，主动调用file.resume()的时候没办法上传，这和我没有用分片上传和MD5计算有关系吗？

**Comment by shady-xia** [comment]
应该是没有关系的， 你可以试试下面这几种方式：
1、在fileAdded之后先file.pause()一下，然后再file.reusme()，试试这样行不行，这是针对于单个文件开始上传的
2、用Uploader.upload() 或者 Uploader.reusme() 试一试，这是针对整个上传器的

**Comment by FuhuaChen** [comment]
onFileAdded (file) {
      file.pause();
      file.resume(); 
},
我尝试在添加图片之后先pause一下在reusme，但是结果好像是一样的，并且在我第一次添加图片时并不会触发上传，在第二次添加图片时就会触发上传，但是是失败的，Uploader.upload()是simple-uploader里的upload()方法吗？我在组件中要怎么调用该方法呢？

**Comment by FuhuaChen** [comment]
通过file.pause()再file.reusme()确实可以解决问题，十分感谢！！
