### ISSUE TITLE
萌新求教

### ISSUE THREAD

**Issue by RuohanXiao** [shady-xia/vue-uploader-solutions#18]
大佬。我现在在使用vue-simple-uploader。我是萌新，求帮忙
1.options里我想带参传输，所以我用了data，但是我想在data中引用现在文件对象里的id，我应该怎么设置？
2.每次我发送请求的时候，
![image](https://user-images.githubusercontent.com/24666680/75745139-5ea7a280-5d51-11ea-8bcb-c7281df8f021.png)都会有个chunk分片，我怎么能阻止这个请求的发送？
3.为了解决问题1，我尝试在@file-added里添加方法，在方法中动态设置options，但是没有成功，请求的时候，file流变成了一个对象，请问我应该怎么办~~

辛苦大佬，我好苦恼啊

**Comment by huzhiqi** [comment]
可以将自定义参数加在uploader实例的opts上，比如
this.$refs.uploader.uploader.opts.query = '12345'

我现在是想在每块添加一个唯一标示，但是多个文件会串掉
