### ISSUE TITLE
关于上传状态

### ISSUE THREAD

**Issue by IMChloe96** [shady-xia/vue-uploader-solutions#2]
项目中如何修改上传状态值 例如一开始是暂停了文件上传是校验MD5而不是暂停

**Comment by IMChloe96** [comment]
上传过程中 暂停了才是显示已暂停 这是在哪里设置的？

**Comment by shady-xia** [comment]
插件中确实没提供这个支持，我的做法是在校验md5的时候手动插入一个text是“检验MD5”的p标签覆盖在.uploader-file-status上，转码完成后移除这个标签。
