### ISSUE TITLE
如何禁用拖拽文件夹

### ISSUE THREAD

**Issue by AaronQianZhenYu** [shady-xia/vue-uploader-solutions#26]
最近收到禁用拖拽文件夹的需求，没有找到对应的api可以禁用；然后我发现，这边默认上传文件夹也是上传的文件夹内部的文件，那么我现在的做法是判断path；如果path内有‘/'，我会视为文件夹，然后忽略内部的file；在fileAdded的时候
 if (file.relativePath.indexOf('/') != '-1') {
                // 存在'/'说明是文件夹
                file.ignored = true;
            } else {
}
那么我在想，可能是因为我对这个不熟悉，不知道作者大大有没有比较优雅的解决方式

**Comment by shady-xia** [comment]
我认为这样处理没什么问题，暂时没找到更好的方式。我本来以为file对象里的isFolder可以判断，但是一直为false -。-

**Comment by qubaolai** [comment]
filesAdded方法中传进来的fileList是文件夹的数组 可以判断isFolder
