### ISSUE TITLE
如果上传的文件小于chunkSize，

### ISSUE THREAD

**Issue by cjlaravel** [shady-xia/vue-uploader-solutions#3]
如果上传的文件小于chunkSize，
例如参数情况：
chunkNumber: 1
chunkSize: 5242880
currentChunkSize: 28999
totalSize: 28999
identifier: 487f7b22f68312d2c1bbc93b1aea445b
filename: 文档.xlsx
relativePath: 文档.xlsx
totalChunks: 1
id: 1111

每次上传过程的最开始，vue-simple-uploader会发送一个get请求，来问服务器我哪些分片已经上传过了，
现在问题是get请求完成了，并不会执行Post上传文件的api了，如果大文件没有问题。

**Comment by shady-xia** [comment]
我上传小文件没遇到这个问题，看了下simple-uploader源码逻辑上也没问题。。
你把testChunks设为false，然后看再上传时是否会发post请求，排查一下问题，
