### ISSUE TITLE
第一块会重复上传，md5的id没传过去每块id都一样的

### ISSUE THREAD

**Issue by chfeizy** [shady-xia/vue-uploader-solutions#30]

**Comment by shady-xia** [comment]
1、之前评论中有人提到过第一个问题，他是testChunks改为了false，但是checkChunkUploadedByResponse这个函数没注释掉，你看看是否对症
2、md5是在file-added方法中对file进行计算的，每个file都应该是不一样的， 检查一下写法；然后再看下是否将md5的值赋给不同的file：file.uniqueIdentifier = 'your md5'

**Comment by chfeizy** [comment]
checkChunkUploadedByResponse这个函数注释分块文件对了，md5看起来是用法有问题，直接是这个文件的md5 不是分块的

**Comment by chfeizy** [comment]
md5分片是按照分片大小来的，但是simple-uploader.js分片最后一片是会超过分片大小，最后一片只要不是分片两倍就会是一片

**Comment by shady-xia** [comment]
为啥要以simple-uploader的分片标准来计算md5呀，直接用File.prototype.slice的方法自己切分文件然后计算md5就好了啊，可以看下我的源码

**Comment by chfeizy** [comment]
应该是说这个md5 是针对这个视频文件的还是针对当前分片的，针对视频你这个没错，如果针对分片应该是计算当前分片的md5
