### ISSUE TITLE
  :auto-start="false" 不生效还是上传了

### ISSUE THREAD

**Issue by EmilyZhang123** [shady-xia/vue-uploader-solutions#33]
:options="options"
    :file-status-text="statusText"
    :auto-start="false"
    class="uploader-example"
    ref="uploader"
    @file-added="onFileAdded"
    @file-success="onFileSuccess"
    @file-error="onFileError"
    @file-removed="fileRemoved"

**Comment by shady-xia** [comment]
没遇到过，有类似的issue：
https://github.com/simple-uploader/vue-uploader/issues/163#issue-933597047
