### ISSUE TITLE
调用上传接口动态传参没有生效

### ISSUE THREAD

**Issue by lisenz** [shady-xia/vue-uploader-solutions#37]
![image](https://user-images.githubusercontent.com/18478465/174929370-ac1de5a8-602d-476a-9c13-b952570af05a.png)

![image](https://user-images.githubusercontent.com/18478465/174929279-2aba9e24-0b5f-4f81-ab36-8eb69923abdf.png)

![image](https://user-images.githubusercontent.com/18478465/174929458-e25a3bc2-0e9b-4aed-815b-40a7d56267d0.png)
你好，如上代码，我在file.params那里已经赋值了从服务端api接口返回的参数，但是在进行上传的接口那里一直没有获取到对应的参数，请问是否哪里写错了？

**Comment by shady-xia** [comment]
你是说在query里拿不到params么，我怀疑可能是因为你是在fileadded里给file异步加参数的缘故，可以试试先pause文件，加完参数再resume。

**Comment by lisenz** [comment]
@shady-xia 确实是这个问题，先pause再resume就可以了，谢谢
