### ISSUE TITLE
夏大师，有没有VUE3版本

### ISSUE THREAD

**Issue by laozhu001** [shady-xia/vue-uploader-solutions#40]

**Comment by myjimmyzhou** [comment]
Vue3会报很多错喔

**Comment by shady-xia** [comment]
近期就会出一个vue3的demo

**Comment by shady-xia** [comment]
https://github.com/shady-xia/vue-uploader-solutions-next

**Comment by laozhu001** [comment]
收到，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shady-xia/vue-uploader-solutions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月5日(星期五) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shady-xia/vue-uploader-solutions] 夏大师，有没有VUE3版本 (Issue #40)





 
https://github.com/shady-xia/vue-uploader-solutions-next
