### ISSUE TITLE
目前的解决方案似乎并不完善？

### ISSUE THREAD

**Issue by naisev** [shady-xia/vue-uploader-solutions#43]
目前看了下，大概有这些问题：
暂停后无法继续?
断点续传似乎并没有实现(node后端未完善?)
上传成功后并没有合并请求?

**Comment by shady-xia** [comment]
1. demo中好像是有这个问题，我瞅瞅
2. node后端代码只是做了个简单的上传，确实没有写秒传，断点续传和合并等逻辑
3. 合并请求是要额外实现的

**Comment by shady-xia** [comment]
感谢反馈，暂停问题已经修复了

**Comment by naisev** [comment]
Thanks!希望未来可以完善下node后端的demo~
