### ISSUE TITLE
python 版本一定要2.x？

### ISSUE THREAD

**Issue by ramseyfeng** [shady-xia/vue-uploader-solutions#45]
下载了这项目，
yarn install报错
看着都和node-saas node-gyp有关，请问这个必须python2?

**Comment by shady-xia** [comment]
node-sass版本的问题，可以把node-sass换成sass，我改一下package.json

**Comment by shady-xia** [comment]
https://github.com/shady-xia/vue-uploader-solutions/commit/ccec5291ebe8fcb78026c53883da8d5125f4559a
