### ISSUE TITLE
是否可以支持断网恢复后可以继续传？

### ISSUE THREAD

**Issue by ramseyfeng** [shady-xia/vue-uploader-solutions#46]
有个场景就是网络不稳定，传个比较大的文件好几个G那种，网络突然中断，想问如何能够支持续传？前端看着resume是不显示已经，请问有啥办法

**Comment by shady-xia** [comment]
做分片和断点续传，插件是支持重传的

**Comment by ramseyfeng** [comment]
@shady-xia 重传只能通过后端判断应该从哪块接着传对吧？
单纯的从前端能指定从第几个chunk开始做不到吧，或者只能调个get结合这篇文章l来达到类似效果对吧：https://www.cnblogs.com/xiahj/p/vue-simple-uploader.html#72-%E5%89%8D%E7%AB%AF%E5%81%9A%E5%88%86%E7%89%87%E6%A3%80%E9%AA%8Ccheckchunkuploadedbyresponse

**Comment by shady-xia** [comment]
对的，后端肯定要记录的，然后前端在checkChunkUploadedByResponse里判断

**Comment by ramseyfeng** [comment]
好的谢谢大佬
