### ISSUE TITLE
请问后端返回200状态码，可是system error，应该如何在processReponse处理

### ISSUE THREAD

**Issue by ramseyfeng** [shady-xia/vue-uploader-solutions#47]
状态码200，可返回自定义错误该如何在processReponse 中处理让文件中断上传？直接丢new Error()?

```
{
    "code": "99999",
    "errorMsg": "System Exception"
}
```

**Comment by shady-xia** [comment]
https://github.com/simple-uploader/Uploader/issues/17
按他这个说法抛出错误然后再在事件中处理应该是可以的，你可以先试试

**Comment by ramseyfeng** [comment]
@shady-xia 感谢回答，可试了直接抛new Error()，在fileError handler里面好像接不到啊
![image](https://user-images.githubusercontent.com/2835062/198816824-fdfa58d2-bf1f-472e-a864-57c9fc4f1f06.png)
![image](https://user-images.githubusercontent.com/2835062/198816841-66b4b0ef-0de6-4195-8da0-ee5f23132038.png)
![image](https://user-images.githubusercontent.com/2835062/198816853-1c883794-3299-4a03-8897-84401b051b5f.png)

**Comment by shady-xia** [comment]
看了下源码，要这样用：`cb(null, response)` 代表成功，`cb(true, response)` 代表失败

**Comment by ramseyfeng** [comment]
谢谢帮忙调查，也看了个代码，processedState 会在后面覆盖。
话说删除文件好像没有个会调的事件？只能通过$refs.uploader.uploader.on('fileRemoved')去做？就想知道获取files的增删改查变化比较好的方式应该怎么做？
通过watch $refs.uploader.uploader.files ? 还是通过CRUD事件？目前有file-added事件，可好像没删除event
趁这个帖子多问个问题哈
或者大佬有啥微信交流群？加了那个QQ的几乎没人交流

**Comment by shady-xia** [comment]
仔细读vue-uploader的文档，「所有的事件都会通过 [lodash.kebabCase](https://github.com/lodash/lodash/blob/master/kebabCase.js) 做转换，例如 fileSuccess 就会变成 file-success」。so删除就用@file-removed事件就好了。
你说加的是插件的官方qq群么？我这没有任何交流群，要不加我微信吧: shady-xia
