### ISSUE TITLE
关于总之上传

### ISSUE THREAD

**Issue by regg1e** [shady-xia/vue-uploader-solutions#5]
请教下 我在一个页面调用这个组件，如果在跳到其他页面，上传还在继续，但是上传了多少那个进度条没有了，怎么处理

**Comment by shady-xia** [comment]
你是想跳到别的页面时，那个上传的窗口还是保留的么，这个要把上传的组件放在app.vue里当做全局的组件。这样窗口相当于一直存在，只不过平时隐藏，上传的时候才会出来

**Comment by kemaosen** [comment]
老哥 你的东西我基本上全部套用了 但是 点击上传按钮 没有任何效果
![image](https://user-images.githubusercontent.com/43406263/56782899-bdd88480-681b-11e9-9d00-172587d9725f.png)
------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/43406263/56782966-0001c600-681c-11e9-9894-db1ed32bccc2.png)
我点击了事件 在当前页面触发了 缺无法在全局吊起上传组件

**Comment by shady-xia** [comment]
1.先确认你在app.vue中注册了globalUploader
2.在globalUploader.vue的Bus.$on('openUploader'...） 里面打个断点或者做个打印数据，然后点击上传，看看这里有没有接收到事件

**Comment by regg1e** [comment]
怎么提升上传速度，我把chunkSize改了，结果参数都传递不到后台了

**Comment by kemaosen** [comment]
感谢回电，我已经使用其他的方式完成了功能。谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [shady-xia/Blog] 关于总之上传 (#5)发件人：Shady 收件人：shady-xia/Blog 抄送：kemaosen ,Comment 1.先确认你在app.vue中注册了globalUploader

2.在globalUploader.vue的Bus.$on('openUploader'...） 里面打个断点或者做个打印数据，然后点击上传，看看这里有没有接收到事件
