### ISSUE TITLE
请问是否有分片上传完成的回掉函数

### ISSUE THREAD

**Issue by oo10** [shady-xia/vue-uploader-solutions#7]
在分片上传时，网络错误是能够通过`.fileError(rootFile, file, message, chunk)`捕捉从而终止。
也有看到针对整个文件的 success 函数 `.fileSuccess(rootFile, file, message, chunk)`。
但是好像找不到单个分片上传完成的回调函数。
也就是说分片接口正常返回200，实际上因为其他验证问题出错的时候无法拿到 res 终止上传。
求助~

**Comment by shady-xia** [comment]
单个分片上传成功会触发fileProgress事件，但是这个事件中没有message参数，可以到simple-uploader上提个issue
