### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by lyj0823** [shady-xia/vue-uploader-solutions#8]
Hi, thanks for your work! But I  am not familiar with how to run this project, can you help me?

**Comment by shady-xia** [comment]
hello, this is just a Vue code snippet for my article, which can't run standalone without a Vue project

**Comment by lyj0823** [comment]
Thanks for your reply, but can you give me some suggestions on how to add these Vue codes in a Vue project? Thanks a lot!

**Comment by shady-xia** [comment]
1、`npm install vue-simple-uploader` ，and follow the documentation to initialize the plugin: https://github.com/simple-uploader/vue-uploader
2、put `globalUploader.vue` in `components ` folder
3、register the `<global-uploader>`  in `app.vue`
4、put `demo.vue` in your page folder, and you can see the effect in this page

**Comment by lyj0823** [comment]
非常感谢您的回复，我尝试一下，因为刚开始接触这一块，可能问题比较基础，谢谢你耐心回答，祝好！




------------------ 原始邮件 ------------------
发件人: "Shady"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午9:44
收件人: "shady-xia/Blog"<Blog@noreply.github.com>; 
抄送: "李元杰"<1321619501@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shady-xia/Blog] How to run? (#8)




1、npm install vue-simple-uploader ，and follow the documentation to initialize the plugin: https://github.com/simple-uploader/vue-uploader
 2、put globalUploader.vue in components  folder
 3、register the <global-uploader>  in app.vue
 4、put demo.vue in your page folder, and you can see the effect in this page

**Comment by shady-xia** [comment]
哈哈，慢慢来~
