### ISSUE TITLE
实时展示md5错误，提示$t('res.checkMD5')找不到

### ISSUE THREAD

**Issue by wangpai1998** [shady-xia/vue-uploader-solutions#9]
@shady-xia [Vue warn]: Error in nextTick: "TypeError: _this3.$t is not a function"
vue.runtime.esm.js?2b0e:1888 TypeError: _this3.$t is not a function

**Comment by shady-xia** [comment]
$t是做多语言的，这里你直接改成中文就好了

**Comment by shady-xia** [comment]
已修复 https://github.com/shady-xia/Blog/commit/0cf8e2351ee5d0ee65f3325c608fa5e0afd682a4

**Comment by wangpai1998** [comment]
谢谢
